PRICE_LEVEL_MAPPING = {
    0: 0,  # PRICE_LEVEL_UNSPECIFIED
    1: 1,  # PRICE_LEVEL_INEXPENSIVE
    2: 2,  # PRICE_LEVEL_MODERATE
    3: 3,  # PRICE_LEVEL_EXPENSIVE
    4: 4,  # PRICE_LEVEL_VERY_EXPENSIVE
    # PRICE_LEVEL_FREE is handled separately
}